### ISSUE TITLE
Large Chicken Eggs AE2 export behaviour

### ISSUE THREAD

**Issue by DietmarKracht** [alkcorp/GTplusplus#469]
# Issue Title  
 The large chicken eggs dont have a value when dropped by a dead chicken. If they enter an inventory other than the players they have "??" as their value and thus cannot be correctly recognized by any export busses although they are oredicted.

## Expected Behavior
The value should be generated at the time the itemstack drops

## Current Behavior
value is generated at the time they enter players inventory

## Steps to Reproduce (for bugs)
 1. Make a big friendly chicken farm.
2. Use Magnet card to let eggs enter the AE2 network before entering the players inventory
3. see "??" eggs in your network

## Game Environment
GTNH 2.0.7.0 DELTA

I

### Misc Info
 Check all that apply ([ ] -> [x] - use a lowercase x)
 - [x]    Using GT:NH/GT:New Horizons?
 - [ ]    Single Player?
 - [x]    Multi Player?

**Comment by draknyte1** [comment]
This is because NBT isn't set until it's held within an inventory, as ground Items are technically Entities, like cows/etc. 

Don't really plan to 'fix' this issue.. 
Besides adding in a new block that will set them when they enter or adding handling for ground items, there's nothing I can think to do to resolve this.

**Comment by botn365** [comment]
![afbeelding](https://user-images.githubusercontent.com/42187820/69084492-a9bcd480-0a44-11ea-8887-c10a91175c1a.png)
re open ticket
