### ISSUE TITLE
Output super bus aren't auto outputting in nearby inventory

### ISSUE THREAD

**Issue by Alexdoru** [alkcorp/GTplusplus#576]
## Expected Behavior
Super bus should be able to auto output in an inventory. This way it would be consistend with normal output bus.
 In my case I have an ME interface on the super bus and it is not outputting in the interface.

## Possible Solution
Make it auto output

## Game Environment
 * Modpack Name:  GTNH 2.0.7.5

**Comment by draknyte1** [comment]
As it turns out, it's special behaviour only found in GTNH, so I wasn't accounting for it.

https://github.com/GTNewHorizons/GT5-Unofficial/blob/4b941fa40fe0830868bead291d49d76e29f74003/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_OutputBus.java#L110

https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_OutputBus.java

**Comment by botn365** [comment]
the auto rotor replacment hatch is way to expansif 
new recipy sugestion
replace the 24 UV conveyor, 32 ZPM motors and 16 ZPM pistons 
with 8 UV conveyor, 4 UV robot arms and 8 UV circuits

why has pikyonium be changed to UV
this makes LuV enegycores and buffers, large scale assembler and toxic everglade
